import Header from "@/components/Header";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-open-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Lochan Saroy",
  description: "Generated by create next app",
};

// If this is a nested layout (e.g. inside a dashboard folder), 
// do not name it RootLayout, just Layout is fine.
export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 1. Replaced <html> and <body> with a React Fragment or simple div wrapper

    // 2. Applied the font class (openSans.className) so your fonts actually work
    <html lang="en">
      <body>


        <div className={`${openSans.className} min-h-screen w-full bg-[#0a0a0a] relative overflow-x-clip`}>

          {/* Background Gradient */}
          <div
            className="fixed inset-0 z-0"
            style={{
              backgroundImage: `radial-gradient(circle 500px at 50% 200px, #0a1d2e, transparent)`,
            }}
          />
          {/* Content */}
          <Header />
          <div className="flex relative   py-20 mx-48">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}